services:
  api-template: # TODO: change this to your project name
   container_name: api-template # TODO: change this to your project name
   build:
    context: .docker/node/
    dockerfile: Dockerfile
   entrypoint: .docker/node/entrypoint.sh
   ports:
     - '3000:3000' # TODO: change this to your project port
     - '7000:7000' # TODO: change this to your project debug port
   volumes:
     - .:/home/node/app
     
  db-template: # TODO: change this to your project name
   container_name: db-template # TODO: change this to your project name
   build:
    context: .docker/postgres/
    dockerfile: Dockerfile
   command: postgres -c log_statement=all
   volumes:
     - ./.docker/postgres/data:/var/lib/postgresql/data
   environment:
    POSTGRES_DB: template
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
   ports:
     - "5432:5432"
